### ISSUE TITLE
import-in-the-middle failing

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/citgm#1031]
`import-in-the-middle` has been failing in most (if not all) of our recent CIs.

Reference: https://ci.nodejs.org/job/citgm-smoker/3350/ (v21.3.0-proposal)

```
not ok 15 test/hook/v18-static-import-assert.mjs
   ---
   stdout: ''
   stderr: |-
     node:internal/process/esm_loader:34
           internalBinding('errors').triggerUncaughtException(
                                     ^
     SyntaxError [Error]: Unexpected token (2:8)
         at pp$4.raise (/home/iojs/tmp/citgm_tmp/edbb86fd-af61-4d53-aa36-c0fc870640d9/import-in-the-middle/node_modules/acorn/dist/acorn.js:3571:15)
         at pp$9.unexpected (/home/iojs/tmp/citgm_tmp/edbb86fd-af61-4d53-aa36-c0fc870640d9/import-in-the-middle/node_modules/acorn/dist/acorn.js:772:10)
         at pp$9.semicolon (/home/iojs/tmp/citgm_tmp/edbb86fd-af61-4d53-aa36-c0fc870640d9/import-in-the-middle/node_modules/acorn/dist/acorn.js:749:68)

not ok 25 test/other/import-executable.mjs
   ---
   stdout: ''
   stderr: |-
     node:internal/process/promises:262
               triggerUncaughtException(err, true /* fromPromise */);
               ^
     AssertionError [ERR_ASSERTION]: Missing expected rejection (TypeError).
         at async file:///home/iojs/tmp/citgm_tmp/edbb86fd-af61-4d53-aa36-c0fc870640d9/import-in-the-middle/test/other/import-executable.mjs:7:3 {
```

Pinging @bengl and @qard

**Comment by targos** [comment]
CI: https://github.com/nodejs/citgm/actions/runs/7057447831
