### ISSUE TITLE
CITGM failures on Windows

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#170]
We've been seeing this issue  on windows. It seems to happen for all modules.

If I do `npm install citgm@1.2.12` the test passes, but it fails with `npm install citgm@1.3.0`, so I'm assuming it's one of https://github.com/nodejs/citgm/commit/5d44fc29b110a03b242601d7cf53676040a2d94f,  https://github.com/nodejs/citgm/commit/0b109939acc5f81805e93ed482c3cdd345979ccc, or https://github.com/nodejs/citgm/commit/67ae086fd744426d376c45f83d6835d8a2243c34. @TheAlphaNerd @bengl 

```
C:\gib\code\node_test>npm install citgm
(node:5972) fs: re-evaluating native module sources is not supported. If you are using the graceful-
fs module, please update it to a more recent version.
C:\gib\code\node_test
└─┬ citgm@1.4.4
  ├── xml-sanitizer@1.1.5
  └── xmlbuilder@8.2.2

npm WARN enoent ENOENT: no such file or directory, open 'C:\gib\code\node_test\package.json'
npm WARN node_test No description
npm WARN node_test No repository field.
npm WARN node_test No README data
npm WARN node_test No license field.

C:\gib\code\node_test>node node_modules\citgm\bin\citgm express
info:    starting            | express
info:    npm:                | Downloading project:
info:                        | https://github.com/expressjs/express/archive/4.14.
info:                        | .0.tar.gz
info:    npm:                | Project downloaded express-4.14.0.tgz
info:    npm:                | install started
warn:    npm-install:        | (node:11816) fs: re-evaluating native module
warn:                        | sources is not supported. If you are using the
warn:                        | graceful-fs module, please update it to a more
warn:                        | recent version.
info:    npm:                | install successfully completed
info:    npm:                | test suite started
error:   failure             | The canary is dead:
error:   failing module(s)   |
error:   module name:        | express
error:   version:            | 4.14.0
error:   error:              | The canary is dead:
error:   error:              | undefinedC:\gib\code\node_test\ibm-6.4.0.0-node-v.
error:                       | 6.4.0-win-x64\node-v6.4.0-win-x64\npm.CMD:1
error:                       | (function (exports, require, module, __filename,
error:                       | __dirname) { :: Created by npm, please don't edit
error:                       | manually.
error:                       | ^
error:                       | SyntaxError: Unexpected token :
error:                       | at Object.exports.runInThisContext (vm.js:76:16)
error:                       | at Module._compile (module.js:528:28)
error:                       | at Object.Module._extensions..js
error:                       | (module.js:565:10)
error:                       | at Module.load (module.js:473:32)
error:                       | at tryModuleLoad (module.js:432:12)
error:                       | at Function.Module._load (module.js:424:3)
error:                       | at Module.runMain (module.js:590:10)
error:                       | at run (bootstrap_node.js:394:7)
error:                       | at startup (bootstrap_node.js:149:9)
error:                       | at bootstrap_node.js:509:3
error:   done                | The smoke test has failed.
```

**Comment by Akpotohwo** [comment]
I've delved further and I can conclude that the breaking commit is this: https://github.com/nodejs/citgm/commit/67ae086fd744426d376c45f83d6835d8a2243c34 . The failures start showing up here.

**Comment by bzoz** [comment]
I have a fix ready for that, I'll open PR in an hour
