### ISSUE TITLE
Modules failing to install on Windows from github.

### ISSUE THREAD

**Issue by Akpotohwo** [nodejs/citgm#224]
When you run citgm and try to grab some modules from github, it fails. I have tried it using appmetrics and bluebird, getting the following in the logs:
**Bluebird**:
```
info: starting            | https://github.com/petkaantonov/bluebird.git
silly: init-detail         |
silly: {
silly:   "raw": "https://github.com/petkaantonov/bluebird.git",
silly:   "scope": null,
silly:   "escapedName": null,
silly:   "name": "4f1879d2e77d9d493f4cab4ab716223356d157ea",
silly:   "rawSpec": "https://github.com/petkaantonov/bluebird.git",
silly:   "spec": "git+https://github.com/petkaantonov/bluebird.git",
silly:   "type": "hosted",
silly:   "hosted": {
silly:     "type": "github",
silly:     "ssh": "git@github.com:petkaantonov/bluebird.git",
silly:     "sshUrl": "git+ssh://git@github.com/petkaantonov/bluebird.git",
silly:     "httpsUrl": "git+https://github.com/petkaantonov/bluebird.git",
silly:     "gitUrl": "git://github.com/petkaantonov/bluebird.git",
silly:     "shortcut": "github:petkaantonov/bluebird",
silly:     "directUrl": "https://raw.githubusercontent.com/petkaantonov/bluebird/master/package.json"
silly:   }
silly: }
verbose: using-node          | C:\Program Files\nodejs\node.EXE
verbose: using-npm           | C:\Program Files\nodejs\npm.CMD
silly: mk.tempdir          | C:\Users\IBM_AD~1\AppData\Local\Temp\1a9ababb-ca6a-47bd-a976-d509ff54da72
silly: npm-view            | No npm package information available
silly: package-meta        |
silly: {
silly:   "repository": {
silly:     "type": "git",
silly:     "url": "git://github.com/petkaantonov/bluebird.git"
silly:   }
silly: }
info: npm:                | Downloading project: https://github.com/petkaantonov/bluebird.git
info: npm:                | Project downloaded bluebird-3.4.6.tgz
silly: gzip-unpack-start   | C:\Users\IBM_AD~1\AppData\Local\Temp\1a9ababb-ca6a-47bd-a976-d509ff54da72\bluebird-3.4.6.tgz
silly: gzip-unpack-end     | C:\Users\IBM_AD~1\AppData\Local\Temp\1a9ababb-ca6a-47bd-a976-d509ff54da72\bluebird-3.4.6.tgz
info: npm:                | install started
verbose: npm-install:        | > bluebird@3.4.6 prepublish C:\Users\IBM_AD~1\AppData\Local\Temp\1a9ababb-ca6a-47bd-a976-d509ff54da72\4f1879d2e77d9d493f4cab4ab716223356d157ea
verbose:                     | > npm run generate-browser-core && npm run generate-browser-full
verbose: npm-install:        | > bluebird@3.4.6 generate-browser-core C:\Users\IBM_AD~1\AppData\Local\Temp\1a9ababb-ca6a-47bd-a976-d509ff54da72\4f1879d2e77d9d493f4cab4ab716223356d157ea                          
verbose:                     | > node tools/build.js --features=core --no-debug --release --zalgo --browser --minify && mv js/browser/bluebird.js js/browser/bluebird.core.js && mv js/browser/bluebird.min.js js/browser/bluebird.core.min.js
warn: npm-install:        | module.js:471
warn:                     | throw err;
warn:                     | ^
warn:                     |
warn:                     | Error: Cannot find module 'C:\Users\IBM_AD~1\AppData\Local\Temp\1a9ababb-ca6a-47bd-a976-d509ff54da72\4f1879d2e77d9d493f4cab4ab716223356d157ea\tools\build.js'
warn:                     | at Function.Module._resolveFilename (module.js:469:15)
warn:                     | at Function.Module._load (module.js:417:25)
warn:                     | at Module.runMain (module.js:604:10)
warn:                     | at run (bootstrap_node.js:394:7)
warn:                     | at startup (bootstrap_node.js:149:9)
warn:                     | at bootstrap_node.js:509:3
warn: npm-install:        |
warn: npm-install:        | npm
warn: npm-install:        | ERR! Windows_NT 6.1.7601                                                                                                                                                              
warn:                     | npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "generate-browser-core"                                     
warn:                     | npm ERR! node v6.9.1                                                                                                                                                                  
warn:                     | npm ERR! npm  v3.10.8                                                                                                                                                                 
warn:                     | npm ERR! code ELIFECYCLE    
```
**appmetrics**:
```
$ ./citgm.js runtimetools/appmetrics -v silly
info: starting            | runtimetools/appmetrics
silly: init-detail         |
silly: {
silly:   "raw": "runtimetools/appmetrics",
silly:   "scope": null,
silly:   "escapedName": null,
silly:   "name": "f37e8eb44dd2be2d360f04ecb20437fd817dfe00",
silly:   "rawSpec": "runtimetools/appmetrics",
silly:   "spec": "github:runtimetools/appmetrics",
silly:   "type": "hosted",
silly:   "hosted": {
silly:     "type": "github",
silly:     "ssh": "git@github.com:runtimetools/appmetrics.git",
silly:     "sshUrl": "git+ssh://git@github.com/runtimetools/appmetrics.git",
silly:     "httpsUrl": "git+https://github.com/runtimetools/appmetrics.git",
silly:     "gitUrl": "git://github.com/runtimetools/appmetrics.git",
silly:     "shortcut": "github:runtimetools/appmetrics",
silly:     "directUrl": "https://raw.githubusercontent.com/runtimetools/appmetrics/master/package.json"
silly:   }
silly: }
verbose: using-node          | C:\Program Files\nodejs\node.EXE
verbose: using-npm           | C:\Program Files\nodejs\npm.CMD
silly: mk.tempdir          | C:\Users\IBM_AD~1\AppData\Local\Temp\ffee011d-bc05-4ce1-938f-8b34eb43684f
silly: npm-view            | No npm package information available
silly: package-meta        |
silly: {
silly:   "repository": {
silly:     "type": "git",
silly:     "url": "git://github.com/runtimetools/appmetrics.git"
silly:   }
silly: }
info: npm:                | Downloading project: runtimetools/appmetrics
error: failure             | Failure getting project from npm
silly: rm.tempdir          | C:\Users\IBM_AD~1\AppData\Local\Temp\ffee011d-bc05-4ce1-938f-8b34eb43684f
error: failing module(s)   |
error: module name:        | f37e8eb44dd2be2d360f04ecb20437fd817dfe00
error: version:            |
error: error:              | Failure getting project from npm
error: error:              |
error: done                | The smoke test has failed.
```
I tried this with both 1.2.0 and 1.6.0

**Comment by GeorgeAdams95** [comment]
@Akpotohwo , what node version, what command are you running ?

**Comment by targos** [comment]
I'm pretty sure this issue is fixed
