### ISSUE TITLE
Potentially drop support for React

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#238]
It would appear that React is now developing primarily using yarn. As such we can not rely on `npm install && npm test` working anymore. It is currently failing on v4.

/cc @tomocchino who may be able to help us make an informed decision

**Comment by TheAlphaNerd** [comment]
I've currently set React to skip in https://github.com/nodejs/citgm/pull/239

This can be reverted once we have a better idea of what is going on

**Comment by spicyj** [comment]
npm should still work correctly. Can you say more about what the error was? I looked at recent Travis runs but don't see anything failing.

**Comment by TheAlphaNerd** [comment]
@spicyj to reproduce on v4.x
```
$ nvm install v4.6.2
$ nvm use v4
$ git clone https://github.com/facebook/react.git
$ git checkout v15.4.0
$ npm install
```
npm install will fail, although running npm-test afterwards will work

```
> flow-bin@0.31.1 postinstall /Users/thealphanerd/code/react/node_modules/flow-bin
> node lib/install.js

module.js:327
    throw err;
    ^

Error: Cannot find module './internal/streams/BufferList'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/thealphanerd/code/react/node_modules/readable-stream/lib/_stream_readable.js:58:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm WARN prefer global marked@0.3.6 should be installed with -g

> spawn-sync@1.0.15 postinstall /Users/thealphanerd/code/react/node_modules/spawn-sync
> node postinstall


> fsevents@1.0.15 install /Users/thealphanerd/code/react/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/thealphanerd/code/react/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/thealphanerd/.nvm/versions/node/v4.6.2/bin/node" "/Users/thealphanerd/.nvm/versions/node/v4.6.2/bin/npm" "i"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! flow-bin@0.31.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flow-bin@0.31.1 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the flow-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flow-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls flow-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thealphanerd/code/react/npm-debug.log
```

**Comment by TheAlphaNerd** [comment]
It would appear that there is some sort of conflict on v4 regarding `readable-stream` and what version is being resolved

**Comment by TheAlphaNerd** [comment]
SO... if I update npm on node v4 to v3.10.10 then everything works fine.

There is definitely something weird going on with dependencies and the npm 2 resolve algo

/cc @nodejs/npm

**Comment by mcollina** [comment]
@TheAlphaNerd it's more likely that they are not testing against npm v2. npm v3 is more forgiving, and yarn has known differences.
