### ISSUE TITLE
Commander test output contains character that Jenkins tap cannot parse

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#251]
```
TAP version 13
ok 1 - commander v2.9.0
  ---
  # > commander@2.9.0 test /private/var/folders/ws/33cmq_g97fv740jjrjxf3xtr0000gn/T/1c5b13b3-df96-4371-8305-a21f47f8febd/commander
  # > make test
  # [90m   test.arguments.js[0m [36mâœ“[0m
  # [90m   test.command.action.js[0m [36mâœ“[0m
  # [90m   test.command.allowUnknownOption.js[0m [36mâœ“[0m
  # [90m   test.command.executableSubcommand.js[0m [36mâœ“[0m
  # [90m   test.command.executableSubcommandDefault.js[0m [36mâœ“[0m
  # [90m   test.command.help.js[0m [36mâœ“[0m
  # [90m   test.command.name.js[0m [36mâœ“[0m
  # [90m   test.command.nohelp.js[0m [36mâœ“[0m
  # [90m   test.literal.args.js[0m [36mâœ“[0m
  # [90m   test.options.args.optional.given.js[0m [36mâœ“[0m
  # [90m   test.options.args.optional.js[0m [36mâœ“[0m
  # [90m   test.options.args.required.js[0m [36mâœ“[0m
  # [90m   test.options.bool.js[0m [36mâœ“[0m
  # [90m   test.options.bool.no.js[0m [36mâœ“[0m
  # [90m   test.options.bool.small.combined.js[0m [36mâœ“[0m
  # [90m   test.options.bool.small.js[0m [36mâœ“[0m
  # [90m   test.options.camelcase.js[0m [36mâœ“[0m
  # [90m   test.options.cflags.js[0m [36mâœ“[0m
  # [90m   test.options.coercion.js[0m [36mâœ“[0m
  # [90m   test.options.commands.js[0m [36mâœ“[0m
  # [90m   test.options.defaults.given.js[0m [36mâœ“[0m
  # [90m   test.options.defaults.js[0m [36mâœ“[0m
  # [90m   test.options.equals.js[0m [36mâœ“[0m
  # [90m   test.options.func.js[0m [36mâœ“[0m
  # [90m   test.options.hyphen.js[0m [36mâœ“[0m
  # [90m   test.options.large-only-with-value.js[0m [36mâœ“[0m
  # [90m   test.options.large-only.js[0m [36mâœ“[0m
  # [90m   test.options.regex.js[0m [36mâœ“[0m
  # [90m   test.variadic.args.js[0m [36mâœ“[0m
  ...
1..1
```
This character is causing Jenkins to fail when parsing the tap:
```
Processing '/var/lib/jenkins/jobs/gibfahn-citgm-smoker-more-platforms/configurations/axis-node/rhel72-s390x/builds/23/tap-master-files/smoker/report.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gibfahn-citgm-smoker-more-platforms/configurations/axis-node/rhel72-s390x/builds/23/tap-master-files/smoker/report.tap].
org.tap4j.parser.ParserException: Error parsing TAP Stream: Error parsing YAML [  # > commander@2.9.0 test /tmp/76ed815c-0f46-4b0b-87f8-f0855070a3d7/commander
  # > make test
  #    test.arguments.js \033[36m✓\033[0m
  #    test.command.action.js \033[36m✓\033[0m
  #    test.command.allowUnknownOption.js \033[36m✓\033[0m
  #    test.command.executableSubcommandDefault.js \033[36m✓\033[0m
  #    test.command.executableSubcommand.js \033[36m✓\033[0m
  #    test.command.help.js \033[36m✓\033[0m
  #    test.command.name.js \033[36m✓\033[0m
  #    test.command.nohelp.js \033[36m✓\033[0m
  #    test.literal.args.js \033[36m✓\033[0m
  #    test.options.args.optional.given.js \033[36m✓\033[0m
  #    test.options.args.optional.js \033[36m✓\033[0m
  #    test.options.args.required.js \033[36m✓\033[0m
  #    test.options.bool.js \033[36m✓\033[0m
  #    test.options.bool.no.js \033[36m✓\033[0m
  #    test.options.bool.small.combined.js \033[36m✓\033[0m
  #    test.options.bool.small.js \033[36m✓\033[0m
  #    test.options.camelcase.js \033[36m✓\033[0m
  #    test.options.cflags.js \033[36m✓\033[0m
  #    test.options.coercion.js \033[36m✓\033[0m
  #    test.options.commands.js \033[36m✓\033[0m
  #    test.options.defaults.given.js \033[36m✓\033[0m
  #    test.options.defaults.js \033[36m✓\033[0m
  #    test.options.equals.js \033[36m✓\033[0m
  #    test.options.func.js \033[36m✓\033[0m
  #    test.options.hyphen.js \033[36m✓\033[0m
  #    test.options.large-only.js \033[36m✓\033[0m
  #    test.options.large-only-with-value.js \033[36m✓\033[0m
  #    test.options.regex.js \033[36m✓\033[0m
  #    test.variadic.args.js \033[36m✓\033[0m
]: special characters are not allowed
	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:230)
	at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:193)
	at org.tap4j.plugin.TapParser.parse(TapParser.java:167)
	at org.tap4j.plugin.TapPublisher.loadResults(TapPublisher.java:540)
	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:412)
	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:371)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: org.tap4j.parser.ParserException: Error parsing YAML [  # > commander@2.9.0 test /tmp/76ed815c-0f46-4b0b-87f8-f0855070a3d7/commander
  # > make test
  #    test.arguments.js \033[36m✓\033[0m
  #    test.command.action.js \033[36m✓\033[0m
  #    test.command.allowUnknownOption.js \033[36m✓\033[0m
  #    test.command.executableSubcommandDefault.js \033[36m✓\033[0m
  #    test.command.executableSubcommand.js \033[36m✓\033[0m
  #    test.command.help.js \033[36m✓\033[0m
  #    test.command.name.js \033[36m✓\033[0m
  #    test.command.nohelp.js \033[36m✓\033[0m
  #    test.literal.args.js \033[36m✓\033[0m
  #    test.options.args.optional.given.js \033[36m✓\033[0m
  #    test.options.args.optional.js \033[36m✓\033[0m
  #    test.options.args.required.js \033[36m✓\033[0m
  #    test.options.bool.js \033[36m✓\033[0m
  #    test.options.bool.no.js \033[36m✓\033[0m
  #    test.options.bool.small.combined.js \033[36m✓\033[0m
  #    test.options.bool.small.js \033[36m✓\033[0m
  #    test.options.camelcase.js \033[36m✓\033[0m
  #    test.options.cflags.js \033[36m✓\033[0m
  #    test.options.coercion.js \033[36m✓\033[0m
  #    test.options.commands.js \033[36m✓\033[0m
  #    test.options.defaults.given.js \033[36m✓\033[0m
  #    test.options.defaults.js \033[36m✓\033[0m
  #    test.options.equals.js \033[36m✓\033[0m
  #    test.options.func.js \033[36m✓\033[0m
  #    test.options.hyphen.js \033[36m✓\033[0m
  #    test.options.large-only.js \033[36m✓\033[0m
  #    test.options.large-only-with-value.js \033[36m✓\033[0m
  #    test.options.regex.js \033[36m✓\033[0m
  #    test.variadic.args.js \033[36m✓\033[0m
]: special characters are not allowed
	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:429)
	at org.tap4j.parser.Tap13Parser.parseLine(Tap13Parser.java:262)
	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:224)
	... 15 more
Caused by: unacceptable character '' (0x1B) special characters are not allowed
in "'string'", position 99
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:424)
	... 17 more
```
We need to ideally find a way to filter these out

**Comment by GeorgeAdams95** [comment]
@TheAlphaNerd not sure if you think that this is something that CITGM should be able to handle or whether we should just get command to stop using the character?

**Comment by gibfahn** [comment]
I'd assume that control characters are used quite pervasively for coloured output in terminals, I'm not sure why this issue only seems to be showing up in commander.

**Comment by Fishrock123** [comment]
Usually there is an env variable or such that prevents such characters from being output to non-pseudo-terminals.

**Comment by gibfahn** [comment]
@Fishrock123 I don't think there is for Commander, the test runner is [here](https://github.com/tj/commander.js/blob/c6236d9504b60d9a2e6aa7fc3ce17a12f48f4a3e/test/run).
