### ISSUE TITLE
CitGM failures on master

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#288]
[I ran the CitGM job against master](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/483/) to make sure everything was working. Two issues:

 - The osx job got stuck at this point (I had to abort it):
```
info: done                | The test suite for full-icu-test version 1.0.1 passed.
info: starting            | sqlite3             
verbose: using-uid           | 502                 
verbose: using-gid           | 20                  
verbose: using-node          | /Users/iojs/build/workspace/citgm-smoker/nodes/osx1010/smoker/bin/node
verbose: using-npm           | /Users/iojs/build/workspace/citgm-smoker/nodes/osx1010/smoker/bin/npm
info: npm:                | Downloading project: https://github.com/mapbox/node-sqlite3/archive/v3.1.8.tar.gz
info: npm:                | Project downloaded sqlite3-3.1.8.tgz
info: npm:                | install started     
verbose: nodedir             | Using --nodedir="/Users/iojs/build/workspace/citgm-smoker/nodes/osx1010"
```

 - Failure on Ubuntu-16.04 (libxmljs)

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/483/nodes=ubuntu1604-64/testReport/junit/(root)/citgm/libxmljs_v0_18_0/

```
 ✔ errors - empty_html_doc
 ✔ validate_memory_usage
 ✔ fromHtml
 ✔ fromHtmlFragment
 [31m✖ validate_rng_memory_usage[39m
 AssertionError
     at Object.ok (/tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/lib/types.js:83:39)
     at Object.module.exports.validate_rng_memory_usage (/tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/test/document.js:394:12)
     at Object.<anonymous> (/tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/lib/core.js:236:16)
     at /tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/lib/core.js:236:16
     at Object.exports.runTest (/tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/lib/core.js:70:9)
     at /tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/lib/core.js:118:25
     at /tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/deps/async.js:513:13
     at iterate (/tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/deps/async.js:123:13)
     at /tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/deps/async.js:134:25
     at /tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/deps/async.js:515:17
     at Immediate.<anonymous> (/tmp/81eea01d-b85b-468f-8949-541b2808edf0/libxmljs/node_modules/nodeunit/lib/types.js:146:17)
     at runCallback (timers.js:651:20)
     at tryOnImmediate (timers.js:624:5)
     at processImmediate [as _immediateCallback] (timers.js:596:5)
 [1melement[22m
```

**Comment by GeorgeAdams95** [comment]
sqlite3 is new but should run fine on osx, not sure about the other one

**Comment by TheAlphaNerd** [comment]
@gibfahn can you try running the test suite locally on ubuntu for libxmljs... would be nice to see if we can reproduce

**Comment by gdams** [comment]
@gibfahn any update testing libxmljs?

**Comment by gdams** [comment]
libxmljs-0.18.4 seems to be fully working on Ubuntu-16.04 now
