### ISSUE TITLE
node-sass error not shown in citgm output

### ISSUE THREAD

**Issue by mscdex** [nodejs/citgm#387]
* **Node Version**: master
* **CitGM Version**: latest?
* **Platform**: node CI

I've noticed that when node-sass's test suite fails, it seems like the actual error gets truncated, as if the process is exiting too early and all of the stderr or whatever output is not getting written. I have seen this happen several times now. Example: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/633/nodes=debian8-64/consoleFull

Snippet from the above link:

```
...
error:                     | ✓ issue_1171                                                                                                                                                                     
error:                     | ✓ issue_1178                                                                                                                                                                     
error:                     | ✓ issue_1188                                                                                                                                                                     
error:                     | ✓ issue_1192                                                                                                                                                                     
error:                     | ✓ issue_1206                                                                                                                                                                     
error:                     | ✓ issue_1207                                                                                                                                                                     
error:                     | ✓ issue_1208                                                                                                                                                                     
error:                     | ✓ issue_1214                                                                                                                                                                     
error:                     | ✓ issue_1215                                                                                                                                                                     
Build step 'Conditional steps (multiple)' marked build as failure
```

**Comment by gibfahn** [comment]
@mscdex did you resolve this?

**Comment by mscdex** [comment]
I believe the errors were shown much earlier in the output, which is unfortunate as it makes it harder to find out what went wrong.

**Comment by gibfahn** [comment]
Did you find the [Junit output](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/633/nodes=debian8-64/testReport/junit/(root)/citgm/node_sass_v4_5_0/) helpful? 

```
 5835 passing (30s)
   701 pending
   2 failing
   1) binding missing error should be useful:
      Error: Node Sass does not yet support your current environment: Unsupported platform (Linux) 64-bit with Node.js 6.x
 For more information on which environments are supported please see:
 https://github.com/sass/node-sass/releases/tag/v4.5.0
       at module.exports (lib/binding.js:13:13)
       at test/binding.js:15:22
       at _tryBlock (assert.js:379:5)
       at _throws (assert.js:398:12)
       at Function.throws (assert.js:428:3)
       at Context.<anonymous> (test/binding.js:14:14)
   2) binding missing error should list currently installed bindings:
      Error: Node Sass does not yet support your current environment: Unsupported platform (Linux) 64-bit with Node.js 6.x
 For more information on which environments are supported please see:
 https://github.com/sass/node-sass/releases/tag/v4.5.0
       at module.exports (lib/binding.js:13:13)
       at test/binding.js:27:22
       at _tryBlock (assert.js:379:5)
       at _throws (assert.js:398:12)
       at Function.throws (assert.js:428:3)
       at Context.<anonymous> (test/binding.js:26:14)
 DEPRECATION WARNING: Passing red, a non-string value, to unquote()
 will be an error in future versions of Sass.
         on line 8 of /tmp/fdb47503-7abb-4098-9759-a30fc413c8c5/node-sass/node_modules/sass-spec/spec/colors/basic/input.scss
 /tmp/fdb47503-7abb-4098-9759-a30fc413c8c5/node-sass/node_modules/sass-spec/spec/errors/fn-debug/ruleset/input.scss:2 DEBUG: debug
 /tmp/fdb47503-7abb-4098-9759-a30fc413c8c5/node-sass/node_modules/sass-spec/spec/errors/fn-debug/simple/input.scss:1 DEBUG: debug
 WARNING: warn
```

**Comment by mscdex** [comment]
That's eventually what I found.
