### ISSUE TITLE
Multiple modules failing on AIX - bluebird

### ISSUE THREAD

**Issue by gdams** [nodejs/citgm#438]
* **Node Version**: 6
* **CitGM Version**: 2.0.1
* **Platform**: AIX

We are seeing several modules failing on AIX due to not being able to find bluebird:

``` bash
     throw err;
     ^
 Error: Cannot find module 'bluebird'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/ramdisk0/citgm/6bc27fe6-b33e-4644-8ef7-f8faaee33171/graceful-fs/node_modules/tap/lib/test.js:9:15)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
 npm ERR! Test failed.  See above for more details.
```

**Comment by gdams** [comment]
example: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/MACHINE=aix61-ppc64/155/testReport/%28root%29/citgm/graceful_fs_v4_1_11/

**Comment by refack** [comment]
I see this allot (I believe it's not just on AIX 🤔 )

**Comment by MylesBorins** [comment]
I've seen this on aix a handful of times... looks like an npm issue to me

/cc @nodejs/npm

**Comment by zkat** [comment]
🤔 we do have some reports of deps going MIA. idk what about this specific one, though.

**Comment by BethGriggs** [comment]
Closing as stale
