### ISSUE TITLE
sodium-native failing in v2.0.0

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#496]
* **Node Version**: 8.9.0 (maybe all)
* **CitGM Version**: 2.0.14
* **Platform**: all

```bash
▶ citgm sodium-native                                     ~/wrk/com/DANGER/node 7s (v8.9.1-proposal)
info:    starting            | sodium-native       
info:    lookup              | sodium-native       
info:    lookup-found        | sodium-native       
info:    sodium-native lookup-replace| https://github.com/sodium-friends/sodium-native/archive/v2.0.0.tar.gz
info:    sodium-native npm:  | Downloading project: https://github.com/sodium-friends/sodium-native/archive/v2
info:    sodium-native npm:  | Project downloaded sodium-native-2.0.0.tgz
info:    sodium-native npm:  | npm install started 
warn:    sodium-native npm-install:| ./configure: line 3: ./autogen.sh: No such file or directory
warn:    sodium-native npm-install:| ./configure: line 4: ./configure: No such file or directory
warn:    sodium-native npm-install:| /private/var/folders/r3/dz9sw1tx3zj93kk3d8y18c9h0000gn/T/d44bba82
warn:                              | if (err) throw err                                                       
warn:                              | ^                                                                        
warn:                              |                                                                          
warn:                              | Error: ./configure exited with 127                                       
warn:                              | at ChildProcess.<anonymous> (/private/var/folders/r3/dz9sw1tx3zj93kk3d8y1
warn:                              | at emitTwo (events.js:126:13)                                            
warn:                              | at ChildProcess.emit (events.js:214:7)                                   
warn:                              | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
warn:    sodium-native npm-install:| npm                 
warn:    sodium-native npm-install:| ERR! code ELIFECYCLE
warn:                              | npm ERR! errno 1    
warn:    sodium-native npm-install:| npm ERR!            
warn:    sodium-native npm-install:| sodium-native@2.0.0 install: `node-gyp-build "node preinstall.js"
warn:                              | npm ERR! Exit status 1                                                   
warn:                              | npm ERR!                                                                 
warn:                              | npm ERR! Failed at the sodium-native@2.0.0 install script.               
warn:                              | npm ERR! This is probably not a problem with npm. There is likely additio
warn:    sodium-native npm-install:|                     
warn:    sodium-native npm-install:| npm ERR! A complete log of this run can be found in:             
warn:                              | npm ERR!     /Users/gib/.cache/npm/_logs/2017-11-07T18_01_56_938Z-debug.l
error:   failure             | Install Failed      
error:   failing module(s)   |                     
error:   module name:        | sodium-native       
error:   version:            | 2.0.0               
error:   error:              | Install Failed      
error:   error:              | undefined                                                              
error:                       | > sodium-native@2.0.0 install /private/var/folders/r3/dz9sw1tx3zj93kk3d8y18c9h0
error:                       | > node-gyp-build "node preinstall.js" "node postinstall.js"                    
error:                       |                                                                                
error:                       |                                                                                
error:                       | ./configure: line 3: ./autogen.sh: No such file or directory                   
error:                       | ./configure: line 4: ./configure: No such file or directory                    
error:                       | /private/var/folders/r3/dz9sw1tx3zj93kk3d8y18c9h0000gn/T/d44bba82-4368-49fb-b17
error:                       | if (err) throw err                                                             
error:                       | ^                                                                              
error:                       |                                                                                
error:                       | Error: ./configure exited with 127                                             
error:                       | at ChildProcess.<anonymous> (/private/var/folders/r3/dz9sw1tx3zj93kk3d8y18c9h00
error:                       | at emitTwo (events.js:126:13)                                                  
error:                       | at ChildProcess.emit (events.js:214:7)                                         
error:                       | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)      
error:                       | npm ERR! code ELIFECYCLE                                                       
error:                       | npm ERR! errno 1                                                               
error:                       | npm ERR! sodium-native@2.0.0 install: `node-gyp-build "node preinstall.js" "nod
error:                       | npm ERR! Exit status 1                                                         
error:                       | npm ERR!                                                                       
error:                       | npm ERR! Failed at the sodium-native@2.0.0 install script.                     
error:                       | npm ERR! This is probably not a problem with npm. There is likely additional lo
error:                       |                                                                                
error:                       | npm ERR! A complete log of this run can be found in:                           
error:                       | npm ERR!     /Users/gib/.cache/npm/_logs/2017-11-07T18_01_56_938Z-debug.log    
error:   done                | The smoke test has failed.
info:    duration            | test duration: 12067ms
```

cc/ @mafintosh @emilbayes

**Comment by MylesBorins** [comment]
this seems to me like some files are not being included in the tar ball, will dig in tomorrow

**Comment by MylesBorins** [comment]
Dug in more, this is due to sodium-native now requiring a git submodule to build

I've removed it from the lookup, but we can revisit adding it again

/cc @mafintosh @emilbayes

**Comment by MylesBorins** [comment]
Looks like https://github.com/sodium-friends/sodium-native/issues/43 might be the reason for the failures, up for reverting 0cc3b6f6074847bb562a7ccdf6e6304e0b5308c7 if it is fixed

**Comment by emilbayes** [comment]
I think this issue is that we have scripts for pulling libsodium as a git submodule, and since you download the source zip from github, you will need to run this step: https://github.com/sodium-friends/sodium-native/blob/19a4e2b350e905b9d916699ba4fb78a4b9975e44/package.json#L22

**Comment by MylesBorins** [comment]
Unfortunately we don't support anything custom beyond "npm install && npm
test"

Keep in mind that if this does not work in your release tarballs people
will be unable to install and run tests from them

**Comment by gibfahn** [comment]
>Unfortunately we don't support anything custom beyond "npm install && npm test"

I feel like `git clone --recursive && npm install && npm test` isn't an unreasonable use case, I think submodules are a way better solution than vendoring everything, and I'm not sure bloating your releases with test artifacts is necessarily a good idea.

**Comment by richardlau** [comment]
Time to revisit now we have `useGitClone`?
