### ISSUE TITLE
Look into mocha failures

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#530]
Mocha doesn't seem to work with citgm anymore... ~~it seems like `ci-mode` is disabled, which is causing a clean exit without running the suite on some platforms... but other platforms are simply failing.~~

/cc @boneskull

here's a run of v6.x with mocha

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/229/

edit:

looks like it may be working on some platforms, but not others... a bit confusing.

**Comment by gibfahn** [comment]
Looking at this now.

This is complicated by the fact that canvas is an optional dependency, so it can fail, but phantomjs-prebuilt is not, so if there isn't a prebuilt binary for your system then it fails.

```
> canvas@1.6.9 install /home/gib/mocha-6b9ddc64e27d8700aa6d2cc8d0bb4b47b32d6768/node_modules/histogram/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/dev/shm/usenode.gib/node-v6.12.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.12.60-52.54-default
gyp ERR! command "/dev/shm/usenode.gib/node-v6.12.3-linux-x64/bin/node" "/dev/shm/usenode.gib/node-v6.12.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gib/mocha-6b9ddc64e27d8700aa6d2cc8d0bb4b47b32d6768/node_modules/histogram/node_modules/canvas
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> canvas@1.6.5 install /home/gib/mocha-6b9ddc64e27d8700aa6d2cc8d0bb4b47b32d6768/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/dev/shm/usenode.gib/node-v6.12.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.12.60-52.54-default
gyp ERR! command "/dev/shm/usenode.gib/node-v6.12.3-linux-x64/bin/node" "/dev/shm/usenode.gib/node-v6.12.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gib/mocha-6b9ddc64e27d8700aa6d2cc8d0bb4b47b32d6768/node_modules/canvas
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 (node_modules/histogram/node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.9 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.5 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by boneskull** [comment]
PhantomJS will be gone with v5.0.0 which I hope to release tomorrow

**Comment by boneskull** [comment]
However... 

`canva` is an optional dependency of whatever depends on it.  `canva` is not the problem, though we thought it was at first.

Looking more closely at our build, [sharp](https://npm.im/sharp) now gets installed, which won't build on a 32-bit Node.js without installing a bunch of extra crap.  We have not yet got our hands dirty in aforementioned crap.

In short: Mocha's dev deps will no longer install correctly on 32-bit Node.js, and it's probably up to us to fix it, but it's not even on the radar right now.  This is the first complaint I've heard about it, which puts it on the radar, but don't know if citgm has a way to get around this.

**Comment by boneskull** [comment]
@MylesBorins original link 404s
