### ISSUE TITLE
Lodash v4.0.0 fails

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#61]
perhaps @jdalton can chime in
```
verbose:                     |
verbose:                     | Error: Cannot find module '../lib/fp/convert.js'
verbose:                     | at Function.Module._resolveFilename
verbose:                     | (module.js:325:15)
verbose:                     | at Function.Module._load (module.js:276:25)
verbose:                     | at Module.require (module.js:353:17)
verbose:                     | at require (internal/module.js:12:17)
verbose:                     | at Object.<anonymous>
verbose:                     | (/private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq4…
verbose:                     | 0000gn/T/1287562e-5561-4d58-8c21-eb82a940002f/lod…
verbose:                     | ash/test/test-fp.js:47:28)
verbose:                     | at Object.<anonymous>
verbose:                     | (/private/var/folders/ty/q7q6b07j5r3c7nvnpzm6hkq4…
verbose:                     | 0000gn/T/1287562e-5561-4d58-8c21-eb82a940002f/lod…
verbose:                     | ash/test/test-fp.js:931:3)
verbose:                     | at Module._compile (module.js:397:26)
verbose:                     | at Object.Module._extensions..js
verbose:                     | (module.js:404:10)
verbose:                     | at Module.load (module.js:343:32)
verbose:                     | at Function.Module._load (module.js:300:12)
```

**Comment by TheAlphaNerd** [comment]
looks like the test suite is failing on master as well :(

**Comment by TheAlphaNerd** [comment]
Issue over on lodash tracker https://github.com/lodash/lodash/issues/1841
