### ISSUE TITLE
Travis CI currently broken

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#679]
Travis CI runs on master and recent PRs have test failures.

e.g. https://travis-ci.com/nodejs/citgm/branches
![image](https://user-images.githubusercontent.com/5445507/52841278-cada4880-30f3-11e9-869c-fbe1f24b6b2c.png)

[Build #253](https://travis-ci.com/nodejs/citgm/builds/99174006):
https://travis-ci.com/nodejs/citgm/jobs/174170189#L462-L496
```
> citgm@3.4.8 tap /home/travis/build/nodejs/citgm
> tap -J --timeout 240 "test/**/test-*.js" "--coverage" "--coverage-report=lcov"
/home/travis/build/nodejs/citgm/lib/package-manager/test.js:1
ReferenceError: _ad4‍ is not defined
    at Function.__get__ (/home/travis/build/nodejs/citgm/lib/package-manager/test.js:8:21)
    at Object.<anonymous> (/home/travis/build/nodejs/citgm/test/npm/test-npm-author-name.js:8:28)
    at Generator.next (<anonymous>)
/home/travis/build/nodejs/citgm/lib/lookup.js:31
// Pull the repository url either from the lookup table
                    ^
/home/travis/build/nodejs/citgm/lib/lookup.js:1
ReferenceError: _ad4‍ is not defined
    at Function.__get__ (/home/travis/build/nodejs/citgm/lib/lookup.js:31:21)
    at Object.<anonymous> (/home/travis/build/nodejs/citgm/test/test-lookup.js:8:24)
    at Generator.next (<anonymous>)
test/bin/test-citgm-all.js .......................... 18/18 2m
test/bin/test-citgm.js ................................ 8/8 44s
test/npm/test-npm-author-name.js ...................... 0/1
  not ok test/npm/test-npm-author-name.js
    timeout: 240000
    file: test/npm/test-npm-author-name.js
    childId: 2
    command: /home/travis/.nvm/versions/node/v11.8.0/bin/node
    args:
      - '-r'
      - /home/travis/build/nodejs/citgm/node_modules/esm/esm.js
      - test/npm/test-npm-author-name.js
    stdio:
      - 0
      - pipe
      - 2
    cwd: /home/travis/build/nodejs/citgm
    exitCode: 1
```

**Comment by richardlau** [comment]
This looks like it's related to `rewire`:
- https://github.com/jhnns/rewire/issues/158
- https://github.com/tapjs/node-tap/issues/509

**Comment by richardlau** [comment]
Okay it looks like it's `tap`. If I manually rollback to `tap@12.4.1` then our tests run cleanly (but fail just like the CI with `tap@12.5.2`).

**Comment by richardlau** [comment]
New version of `esm` has been released to fix the problem: https://github.com/tapjs/node-tap/issues/509#issuecomment-464123212

Requested a CI run on `master`: https://travis-ci.com/nodejs/citgm/builds/101177628

**Comment by richardlau** [comment]
Well the good news is the original failures appear fixed.

Bad news is we have a test failure on Node.js 11.10.0 (which comes with a new npm): https://travis-ci.com/nodejs/citgm/jobs/178283173#L468-L869

**Comment by richardlau** [comment]
Moved the failure with Node.js 11.10.0 over to https://github.com/nodejs/citgm/issues/680.
