### ISSUE TITLE
Use citgm to test  request  results in -Error  |failure   |The canary is dead.

### ISSUE THREAD

**Issue by smartmouse** [nodejs/citgm#7]
[nodetest@test  vmTest]$ citgm -lv request@latest

# http over https, tunnel=true
not ok 4 should be equivalent
    operator: deepEqual
    expected:      [ 'https connect to localhost:6767', 'http response', '200 ht          tp ok' ]
    actual:      [ 'err tunneling socket could not be established, cause=certifi          cate has expired' ]
    at: Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
  ...
# http over https, tunnel=false
not ok 5 should be equivalent
    operator: deepEqual
    expected: [ 'https proxy to http', 'http response', '200 http ok' ]
    actual:   [ 'err certificate has expired' ]
    at: Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
  ...
# http over https, tunnel=default
not ok 6 should be equivalent
    operator: deepEqual
    expected: [ 'https proxy to http', 'http response', '200 http ok' ]
    actual:   [ 'err certificate has expired' ]
    at: Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
  ...
# https over http, tunnel=true
not ok 7 should be equivalent
    operator: deepEqual
    expected:      [ 'http connect to localhost:16167', 'https response', '200 h          ttps ok' ]
    actual:      [ 'http connect to localhost:16167', 'err certificate has expir          ed' ]
    at: Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
  ...
# https over http, tunnel=false
/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/node_modules/tape/index.js:75
        throw err
              ^
Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

Assert: "should be equivalent",
         found: [ 'err tunneling socket could not be established, cause=certific          ate has expired' ]
        wanted: [ 'https connect to localhost:6767', 'http response', '200 http           ok' ]
        Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
Assert: "should be equivalent",
         found: [ 'err certificate has expired' ]
        wanted: [ 'https proxy to http', 'http response', '200 http ok' ]
        Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
Assert: "should be equivalent",
         found: [ 'err certificate has expired' ]
        wanted: [ 'https proxy to http', 'http response', '200 http ok' ]
        Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)
Assert: "should be equivalent",
         found: [ 'http connect to localhost:16167', 'err certificate has expire          d' ]
        wanted: [ 'http connect to localhost:16167', 'https response', '200 http          s ok' ]
        Request._callback (/tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/tes          ts/test-tunnel.js:134:9)

ok test-unix.js ..................... 3/3
total ......................... 1326/1331

not ok

npm ERR! Linux 2.6.32-431.17.1.el6.s390x
npm ERR! argv "/usr/nodetest/T32_12/bin/node" "/usr/nodetest/T32_12/bin/          npm" "run" "test-ci"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! request@2.60.0 test-ci: `taper tests/test-*.js`
npm ERR! Exit status 5
npm ERR!
npm ERR! Failed at the request@2.60.0 test-ci script 'taper tests/test-*.js'.
npm ERR! This is most likely a problem with the request package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     taper tests/test-*.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls request
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/9eab4220-cc8f-43ca-bb1b-71b791c63a11/request/npm-debug.log
npm ERR! Test failed.  See above for more details.
Error  |failure             |The canary is dead.
Info   |rm.tempdir          |/tmp/9eab4220-cc8f-43ca-bb1b-71
Info   |done                |https://github.com/request/requ
       |                    |.0.tar.gz

**Comment by smartmouse** [comment]
I guess the request packages has issues. Closing this.
