### ISSUE TITLE
body-praser broken on node.js master

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#74]
It is fine on v5

```shell
  176 passing (494ms)
  1 failing

  1) bodyParser.urlencoded() with parameterLimit option with extended: false should work with Infinity limit:

      AssertionError: 0 == 10000
      + expected - actual

      -0
      +10000

      at test/urlencoded.js:666:12
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1525:8)
```

**Comment by TheAlphaNerd** [comment]
looks like it has to do with a change in query-string

**Comment by TheAlphaNerd** [comment]
Broken in this PR
https://github.com/nodejs/node/pull/2288
By This Commit
https://github.com/nodejs/node/commit/27def4faf2fb0c759b7e8800f91627cbbca5fdba

Reverting this commit on master allows the test suite for body-parser to work

**Comment by TheAlphaNerd** [comment]
Issue on body-tracker https://github.com/expressjs/body-parser/issues/155

**Comment by TheAlphaNerd** [comment]
It is worth mentioning that the documentation for querystring.parse does not mention anything about maxKeys not supporting Infinity

**Comment by TheAlphaNerd** [comment]
Fixed by https://github.com/nodejs/node/commit/878bcd43f8f9d3ec0d3403cb1bbe1ba6201a6d84
