### ISSUE TITLE
Travis failing on Windows Node.js 12

### ISSUE THREAD

**Issue by richardlau** [nodejs/citgm#747]
There seems to be persistent failures on Travis with Node.js 12 on Windows. 

e.g. https://travis-ci.com/nodejs/citgm/jobs/223653931#L663-L726
```console
not ok 13 - test/test-citgm.js # time=16728.199ms

  ---

  env: {}

  file: test/test-citgm.js

  timeout: 480000

  command: C:\ProgramData\nvs\node\12.8.0\x64\node.exe

  args:

    - -r

    - C:\Users\travis\build\nodejs\citgm\node_modules\esm\esm.js

    - test/test-citgm.js

  stdio:

    - 0

    - pipe

    - 2

  cwd: C:\Users\travis\build\nodejs\citgm

  exitCode: 1

  ...

{

    # Subtest: citgm: omg-i-pass

        1..2

        ok 1 - it should be omg-i-pass

        ok 2 - it should not exit

    ok 1 - citgm: omg-i-pass # time=7669.252ms

    

    # Subtest: citgm: omg-i-pass from git url

        1..3

        ok 1 - it should be the raw URL

        ok 2 - should be equal

        not ok 3 - Failure getting project from npm

          ---

          found:

            !error

            name: Error

            message: Failure getting project from npm

            stack: >-

              Error: Failure getting project from npm

                  at ChildProcess.<anonymous> (C:\Users\travis\build\nodejs\citgm\lib\grab-project.js:2:1111)

                  at ChildProcess.emit (events.js:203:13)

                  at ChildProcess.EventEmitter.emit (domain.js:476:20)

                  at maybeClose (internal/child_process.js:1021:16)

                  at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

          at:

            line: 54

            column: 9

            file: test/test-citgm.js

            type: Tester

          stack: |

            Tester.<anonymous> (test/test-citgm.js:54:9)

            Tester.run (lib/citgm.js:8:1571)

          source: |2

                .on('fail', (err) => {

                  t.error(err);

            --------^

                })

                .on('end', () => {

          ...

        

        # failed 1 of 3 tests

    not ok 2 - citgm: omg-i-pass from git url # time=5444.991ms

    

    1..2

    # failed 1 of 2 tests

    # time=13130.318ms

}
```
https://travis-ci.com/nodejs/citgm/jobs/223653931#L819-L844
```console
    # Subtest: grab-project: use git clone

        1..1

        not ok 1 - Command failed: git submodule init nullnull

          ---

          stack: |

            makeError (node_modules/execa/index.js:174:9)

            node_modules/execa/index.js:278:16

          at:

            line: 174

            column: 9

            file: node_modules/execa/index.js

            function: makeError

          code: 1

          stdout: null

          stderr: null

          failed: true

          signal: null

          cmd: git submodule init

          timedOut: false

          killed: false

          tapCaught: returnedPromiseRejection

          test: "grab-project: use git clone"

          ...

        

        # failed 1 test

    not ok 7 - grab-project: use git clone # time=2455.082ms
```

I've not been able to replicate these locally.

**Comment by richardlau** [comment]
https://travis-ci.com/nodejs/citgm/jobs/248706513#L687-L776
<details>

```console
not ok 13 - test/test-citgm.js # time=11341.446ms

  ---

  env: {}

  file: test/test-citgm.js

  timeout: 480000

  command: C:\ProgramData\nvs\node\12.13.0\x64\node.exe

  args:

    - -r

    - C:\Users\travis\build\nodejs\citgm\node_modules\esm\esm.js

    - test/test-citgm.js

  stdio:

    - 0

    - pipe

    - 2

  cwd: C:\Users\travis\build\nodejs\citgm

  exitCode: 1

  ...

{

    # Subtest: citgm: omg-i-pass

        1..2

        ok 1 - it should be omg-i-pass

        ok 2 - it should not exit

    ok 1 - citgm: omg-i-pass # time=7172.461ms

    

    # Subtest: citgm: omg-i-pass from git url

        1..3

        ok 1 - it should be the raw URL

        ok 2 - should be equal

        not ok 3 - Failure getting project from npm npm ERR! code 1 npm ERR! Command failed: git submodule update -q --init --recursive npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 21: .: git-sh-setup: file not found npm ERR!   npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\travis\AppData\Roaming\npm-cache\_logs\2019-10-23T16_41_44_977Z-debug.log

          ---

          origin:

            at:

              line: 2

              column: 1416

              file: lib/grab-project.js

              function: ChildProcess.<anonymous>

            stack: |

              ChildProcess.<anonymous> (lib/grab-project.js:2:1416)

            source: |

              'use strict';

          

              const path = require('path');

          found:

            !error

            name: Error

            message: >

              Failure getting project from npm

          

              npm ERR! code 1

          

              npm ERR! Command failed: git submodule update -q --init --recursive

          

              npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 21: .: git-sh-setup: file not found

          

              npm ERR! 

          

          

              npm ERR! A complete log of this run can be found in:

          

              npm ERR!     C:\Users\travis\AppData\Roaming\npm-cache\_logs\2019-10-23T16_41_44_977Z-debug.log

            stack: >-

              Error: 

                  at ChildProcess.<anonymous> (C:\Users\travis\build\nodejs\citgm\lib\grab-project.js:2:1416)

                  at ChildProcess.emit (events.js:210:5)

                  at ChildProcess.EventEmitter.emit (domain.js:476:20)

                  at maybeClose (internal/child_process.js:1021:16)

                  at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

          at:

            line: 54

            column: 9

            file: test/test-citgm.js

            type: Tester

          stack: |

            Tester.<anonymous> (test/test-citgm.js:54:9)

            Tester.run (lib/citgm.js:8:1571)

          source: |2

                .on('fail', (err) => {

                  t.error(err);

            --------^

                })

                .on('end', () => {

          ...

        

        # failed 1 of 3 tests

    not ok 2 - citgm: omg-i-pass from git url # time=4157.684ms

    

    1..2

    # failed 1 of 2 tests

    # time=11341.446ms

}
```
</details>

and 
https://travis-ci.com/nodejs/citgm/jobs/248706513#L868-L901
<details>

```console
    ok 6 - grab-project: module does not exist # time=2159.253ms

    

    # Subtest: grab-project: use git clone

        1..1

        not ok 1 - Command failed with exit code 1: git submodule init

          ---

          stack: |

            makeError (node_modules/execa/lib/error.js:56:11)

            handlePromise (node_modules/execa/index.js:114:26)

            gitClone (lib/git-clone.js:1:3243)

            Test.<anonymous> (test/test-grab-project.js:122:3)

          at:

            line: 56

            column: 11

            file: node_modules/execa/lib/error.js

            function: makeError

          command: git submodule init

          exitCode: 1

          signal: null

          signalDescription: null

          stdout: null

          stderr: null

          failed: true

          timedOut: false

          isCanceled: false

          killed: false

          tapCaught: returnedPromiseRejection

          test: "grab-project: use git clone"

          ...

        

        # failed 1 test

    not ok 7 - grab-project: use git clone # time=2103.968ms

    

    # Subtest: grab-project: fail with bad ref
```
</details>

suggest an issue running `git` commands. Searching for `git-sh-setup: file not found` suggests adding the following to the `PATH` environment variable:

-    C:\Program Files\Git\usr\bin
-    C:\Program Files\Git\mingw64\libexec\git-core
