### ISSUE TITLE
citgm.through2-v4.0.1 failing on multiple platforms

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/citgm#809]
- **Node Version**: multiple
- **CitGM Version**: 7.0.0
- **Platform**: multiple

through2 appears to be failing on many platforms across all release lines with the following error:

```bash
 /home/iojs/tmp/citgm_tmp/32c9f2d6-33d9-47a5-a794-ef0983c8a8de/through2/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
 TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
     at onClose (/home/iojs/tmp/citgm_tmp/32c9f2d6-33d9-47a5-a794-ef0983c8a8de/through2/node_modules/puppeteer/lib/Launcher.js:750:14)
     at Interface.<anonymous> (/home/iojs/tmp/citgm_tmp/32c9f2d6-33d9-47a5-a794-ef0983c8a8de/through2/node_modules/puppeteer/lib/Launcher.js:739:50)
     at Interface.emit (events.js:326:22)
     at Interface.close (readline.js:424:8)
     at Socket.onend (readline.js:202:10)
     at Socket.emit (events.js:326:22)
     at endReadableNT (_stream_readable.js:1243:12)
     at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2398/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/through2_v4_0_1/

I've not dug in any further yet.

/cc @rvagg

**Comment by richardlau** [comment]
I suspect it's linked to https://github.com/rvagg/through2/commit/164d3f8ac46b5f0328088f4529395160eee08849 and we probably want to avoid the `test:browser` script for Node.js.
