### ISSUE TITLE
SPDY broken on master

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#82]
The entire test suite for SPDY is broken on master
```
verbose:                     | 1) SPDY Client regular h2 ssl mode should send GET
verbose:                     | request:
verbose:                     | Error: timeout of 2000ms exceeded. Ensure the
verbose:                     | done() callback is being called in this test.
verbose: npm-test:           | 2) SPDY Client regular h2 ssl mode "after each"
verbose:                     | hook:
verbose:                     | Uncaught Error: socket hang up
verbose:                     | at TLSSocket.onclose
verbose:                     | (node_modules/spdy-transport/lib/spdy-transport/c…
verbose:                     | onnection.js:186:15)
verbose:                     | at TCP._onclose (net.js:471:12)
verbose:                     |
verbose:                     | 3) SPDY Client regular h2 plain mode should send
verbose:                     | GET request:
verbose:                     | TypeError: Cannot read property 'request' of
verbose:                     | undefined
verbose:                     | at Context.<anonymous> (test/client-test.js:77:26)
verbose:                     |
verbose:                     | 4) SPDY Client regular h2 plain mode should send
verbose:                     | POST request:
verbose:                     | TypeError: Cannot read property 'request' of
verbose:                     | undefined
verbose:                     | at Context.<anonymous> (test/client-test.js:95:26)
verbose:                     |
verbose:                     | 5) SPDY Client regular h2 ssl mode "before each"
verbose:                     | hook for "should receive PUSH_PROMISE":
verbose:                     | TypeError: Cannot read property 'call' of
verbose:                     | undefined
verbose:                     |
verbose:                     |
verbose:                     | 6) SPDY Client regular h2 plain mode should
verbose:                     | receive PUSH_PROMISE:
verbose:                     | TypeError: Cannot read property 'request' of
verbose:                     | undefined
verbose:                     | at Context.<anonymous>
verbose:                     | (test/client-test.js:109:26)
verbose:                     |
verbose:                     | 7)  Uncaught error outside test suite:
verbose:                     | Uncaught TypeError: Cannot read property
verbose:                     | 'currentRetry' of undefined
```

**Comment by TheAlphaNerd** [comment]
Filed an issue over at node-spdy https://github.com/indutny/node-spdy/issues/246

**Comment by TheAlphaNerd** [comment]
fixed
